version: "3.9"

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: megafon
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d megafon"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    image: migrate/migrate
    command: [
      "-path", "/migrations",
      "-database", "postgres://postgres:postgres@db:5432/megafon?sslmode=disable",
      "up"
    ]
    volumes:
      - ./migrations:/migrations
    depends_on:
      db:
        condition: service_healthy

  bot:
    build:
      context: .
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PG_DSN=postgres://postgres:postgres@db:5432/megafon?sslmode=disable
      - CONFIG_PATH=/config/config.dev.yaml
    restart: always

volumes:
  postgres_data:
