logging:
  level: "debug"          # debug | info | warn | error | dpanic | panic | fatal
  format: "console"         # json  | console
  output_path: "stdout"
  service: "megafon-reports"
  env: "dev"

telegram: {}

megafon_buisness: {}

postgres:
  dsn: "postgres://postgres:postgres@db:5432/megafon?sslmode=disable"
  max_open_conns: 10
  max_idle_conns: 5
  conn_max_lifetime: "30m"
  migrations_dir: "./migrations"